[package]
name = "aoe2rec"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.0"
chrono = "0.4.38"
clap = { version = "4.5.13", features = ["derive"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
yazi = "0.2.0"
