[package]
name = "aoe2rec-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
aoe2rec = { version = "0.1.0", path = "crates/aoe2rec" }

[workspace]
members = ["crates/aoe2js", "crates/aoe2rec"]
