[package]
name = "aoe2js"
version = "0.1.0"
edition = "2021"

[dependencies]
aoe2rec = { version = "0.1.0", path = "../aoe2rec" }
clap = { version = "4.5.20", features = ["derive"] }
serde_json = "1.0.132"
